# docker-compose.yml
version: '3.3'
services:
  postgres:
    image: postgres:13.5
    restart: always
    environment:
      - POSTGRES_USER=lyagroup
      - POSTGRES_PASSWORD=senha123
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
volumes:
  postgres:
